version: '3.5'
services:
  front:
    container_name: instagram_front
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
    - "3000:80"
    volumes:
    - ./build:/usr/share/nginx/html:rw
    - ./docker/nginx.conf:/etc/nginx/nginx.conf